//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace RevolutionDAL
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Character))]
    [KnownType(typeof(PersonalityType))]
    public partial class CharacterPersonality
    {
        [DataMember]
        public int CharacterID { get; set; }
        [DataMember]
        public int PersonalityTypeID { get; set; }
        [DataMember]
        public int Rating { get; set; }
    
        [DataMember]
        public virtual Character Character { get; set; }
        [DataMember]
        public virtual PersonalityType PersonalityType { get; set; }
    }
    
}
