//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace RevolutionDAL
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(CharacterPersonality))]
    public partial class Character
    {
        public Character()
        {
            this.CharacterPersonalities = new HashSet<CharacterPersonality>();
        }
    
        [DataMember]
        public int ID { get; set; }
        [DataMember]
        public string FirstName { get; set; }
        [DataMember]
        public string LastName { get; set; }
        [DataMember]
        public bool Gender { get; set; }
        [DataMember]
        public bool Deleted { get; set; }
    
        [DataMember]
        public virtual ICollection<CharacterPersonality> CharacterPersonalities { get; set; }
    }
    
}
