//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace RevolutionDAL
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(ScopeNode))]
    public partial class Group
    {
        [DataMember]
        public int ID { get; set; }
        [DataMember]
        public string Name { get; set; }
        [DataMember]
        public string Description { get; set; }
        [DataMember]
        public Nullable<int> ScopeNodeID { get; set; }
        [DataMember]
        public bool Deleted { get; set; }
    
        [DataMember]
        public virtual ScopeNode ScopeNode { get; set; }
    }
    
}
