//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Objects;

namespace RevolutionDAL
{
    public partial class RevolutionEntities1 : DbContext
    {
        public RevolutionEntities1()
            : this(false) { }
    
        public RevolutionEntities1(bool proxyCreationEnabled)	    
            : base("name=RevolutionEntities1")
        {
            this.Configuration.ProxyCreationEnabled = proxyCreationEnabled;
        }
    
        public RevolutionEntities1(string connectionString)
          : this(connectionString, false) { }
    
        public RevolutionEntities1(string connectionString, bool proxyCreationEnabled)
            : base(connectionString)
        {
            this.Configuration.ProxyCreationEnabled = proxyCreationEnabled;
        }	
    
        public ObjectContext ObjectContext
        {
          get { return ((IObjectContextAdapter)this).ObjectContext; }
        }
    
    	protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    	
        public DbSet<Character> Characters { get; set; }
        public DbSet<CharacterPersonality> CharacterPersonalities { get; set; }
        public DbSet<PersonalityPhrase> PersonalityPhrases { get; set; }
        public DbSet<PersonalityType> PersonalityTypes { get; set; }
        public DbSet<PersonalityTypeType> PersonalityTypeTypes { get; set; }
        public DbSet<Phrase> Phrases { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Topic> Topics { get; set; }
        public DbSet<Group> Groups { get; set; }
        public DbSet<Region> Regions { get; set; }
        public DbSet<ScopeNode> ScopeNodes { get; set; }
        public DbSet<ScopeNodeChildParent> ScopeNodeChildParents { get; set; }
        public DbSet<ScopeNodeReputation> ScopeNodeReputations { get; set; }
        public DbSet<ScopeNodeReputationChildParent> ScopeNodeReputationChildParents { get; set; }
        public DbSet<ScopeNodeType> ScopeNodeTypes { get; set; }
        public DbSet<Town> Towns { get; set; }
    }
}
