//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace RevolutionDAL
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(PersonalityType))]
    [KnownType(typeof(PersonalityTypeType))]
    public partial class PersonalityTypeType
    {
        public PersonalityTypeType()
        {
            this.PersonalityTypes = new HashSet<PersonalityType>();
        }
    
        [DataMember]
        public int ID { get; set; }
        [DataMember]
        public string Name { get; set; }
        [DataMember]
        public string Description { get; set; }
    
        [DataMember]
        public virtual ICollection<PersonalityType> PersonalityTypes { get; set; }
        [DataMember]
        public virtual PersonalityTypeType PersonalityTypeType1 { get; set; }
        [DataMember]
        public virtual PersonalityTypeType PersonalityTypeType2 { get; set; }
    }
    
}
