//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace RevolutionDAL
{
    [DataContract]
    public partial class PersonalityTypeType
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual string Description
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<PersonalityType> PersonalityTypes
        {
            get
            {
                if (_personalityTypes == null)
                {
                    var newCollection = new FixupCollection<PersonalityType>();
                    newCollection.CollectionChanged += FixupPersonalityTypes;
                    _personalityTypes = newCollection;
                }
                return _personalityTypes;
            }
            set
            {
                if (!ReferenceEquals(_personalityTypes, value))
                {
                    var previousValue = _personalityTypes as FixupCollection<PersonalityType>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupPersonalityTypes;
                    }
                    _personalityTypes = value;
                    var newValue = value as FixupCollection<PersonalityType>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupPersonalityTypes;
                    }
                }
            }
        }
        private ICollection<PersonalityType> _personalityTypes;

        #endregion
        #region Association Fixup
    
        private void FixupPersonalityTypes(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (PersonalityType item in e.NewItems)
                {
                    item.PersonalityTypeType = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (PersonalityType item in e.OldItems)
                {
                    if (ReferenceEquals(item.PersonalityTypeType, this))
                    {
                        item.PersonalityTypeType = null;
                    }
                }
            }
        }

        #endregion
    }
}
