//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace RevolutionDAL
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(CharacterPersonality))]
    [KnownType(typeof(PersonalityPhrase))]
    [KnownType(typeof(PersonalityTypeType))]
    public partial class PersonalityType
    {
        public PersonalityType()
        {
            this.CharacterPersonalities = new HashSet<CharacterPersonality>();
            this.PersonalityPhrases = new HashSet<PersonalityPhrase>();
        }
    
        [DataMember]
        public int ID { get; set; }
        [DataMember]
        public string Name { get; set; }
        [DataMember]
        public string Description { get; set; }
        [DataMember]
        public int TypeID { get; set; }
    
        [DataMember]
        public virtual ICollection<CharacterPersonality> CharacterPersonalities { get; set; }
        [DataMember]
        public virtual ICollection<PersonalityPhrase> PersonalityPhrases { get; set; }
        [DataMember]
        public virtual PersonalityTypeType PersonalityTypeType { get; set; }
    }
    
}
