//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace RevolutionDAL
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(PersonalityType))]
    [KnownType(typeof(Phrase))]
    public partial class PersonalityPhrase
    {
        [DataMember]
        public int PhraseID { get; set; }
        [DataMember]
        public int PersonalityTypeID { get; set; }
        [DataMember]
        public int PersonalityRating { get; set; }
        [DataMember]
        public bool RatingIsGreater { get; set; }
    
        [DataMember]
        public virtual PersonalityType PersonalityType { get; set; }
        [DataMember]
        public virtual Phrase Phrase { get; set; }
    }
    
}
