//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace RevolutionDAL
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(PersonalityPhrase))]
    [KnownType(typeof(Topic))]
    public partial class Phrase
    {
        public Phrase()
        {
            this.PersonalityPhrases = new HashSet<PersonalityPhrase>();
        }
    
        [DataMember]
        public int ID { get; set; }
        [DataMember]
        public int Immediacy { get; set; }
        [DataMember]
        public string Text { get; set; }
        [DataMember]
        public bool IsQuestion { get; set; }
        [DataMember]
        public bool IsSpontaneous { get; set; }
        [DataMember]
        public int TopicID { get; set; }
    
        [DataMember]
        public virtual ICollection<PersonalityPhrase> PersonalityPhrases { get; set; }
        [DataMember]
        public virtual Topic Topic { get; set; }
    }
    
}
