//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace RevolutionDAL
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Character))]
    [KnownType(typeof(ScopeNode))]
    [KnownType(typeof(ScopeNodeReputationChildParent))]
    public partial class ScopeNodeReputation
    {
        public ScopeNodeReputation()
        {
            this.ScopeNodeReputationChildParents = new HashSet<ScopeNodeReputationChildParent>();
            this.ScopeNodeReputationChildParents1 = new HashSet<ScopeNodeReputationChildParent>();
        }
    
        [DataMember]
        public int ID { get; set; }
        [DataMember]
        public int CharacterID { get; set; }
        [DataMember]
        public int ScopeNodeID { get; set; }
        [DataMember]
        public double DirectReputation { get; set; }
        [DataMember]
        public double EffectiveReputation { get; set; }
        [DataMember]
        public bool Deleted { get; set; }
    
        [DataMember]
        public virtual Character Character { get; set; }
        [DataMember]
        public virtual ScopeNode ScopeNode { get; set; }
        [DataMember]
        public virtual ICollection<ScopeNodeReputationChildParent> ScopeNodeReputationChildParents { get; set; }
        [DataMember]
        public virtual ICollection<ScopeNodeReputationChildParent> ScopeNodeReputationChildParents1 { get; set; }
    }
    
}
