//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace RevolutionDAL
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(ScopeNodeChildParent))]
    [KnownType(typeof(ScopeNodeReputation))]
    public partial class ScopeNodeReputationChildParent
    {
        [DataMember]
        public int ID { get; set; }
        [DataMember]
        public int ParentID { get; set; }
        [DataMember]
        public int ChildID { get; set; }
        [DataMember]
        public int ScopeNodeChildParentID { get; set; }
        [DataMember]
        public double RepFromChildMultiplier { get; set; }
        [DataMember]
        public double RepFromParentMultiplier { get; set; }
        [DataMember]
        public bool Deleted { get; set; }
    
        [DataMember]
        public virtual ScopeNodeChildParent ScopeNodeChildParent { get; set; }
        [DataMember]
        public virtual ScopeNodeReputation ScopeNodeReputation { get; set; }
        [DataMember]
        public virtual ScopeNodeReputation ScopeNodeReputation1 { get; set; }
    }
    
}
