//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace RevolutionDAL
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Character))]
    [KnownType(typeof(Group))]
    [KnownType(typeof(Region))]
    [KnownType(typeof(ScopeNode))]
    [KnownType(typeof(ScopeNodeType))]
    [KnownType(typeof(ScopeNodeChildParent))]
    [KnownType(typeof(ScopeNodeReputation))]
    [KnownType(typeof(Town))]
    public partial class ScopeNode
    {
        public ScopeNode()
        {
            this.Characters = new HashSet<Character>();
            this.Groups = new HashSet<Group>();
            this.Regions = new HashSet<Region>();
            this.ScopeNodeChildParents = new HashSet<ScopeNodeChildParent>();
            this.ScopeNodeChildParents1 = new HashSet<ScopeNodeChildParent>();
            this.ScopeNodeReputations = new HashSet<ScopeNodeReputation>();
            this.Towns = new HashSet<Town>();
        }
    
        [DataMember]
        public int ID { get; set; }
        [DataMember]
        public int ScopeNodeTypeID { get; set; }
        [DataMember]
        public int ScopeObjectID { get; set; }
        [DataMember]
        public bool Deleted { get; set; }
    
        [DataMember]
        public virtual ICollection<Character> Characters { get; set; }
        [DataMember]
        public virtual ICollection<Group> Groups { get; set; }
        [DataMember]
        public virtual ICollection<Region> Regions { get; set; }
        [DataMember]
        public virtual ScopeNode ScopeNode1 { get; set; }
        [DataMember]
        public virtual ScopeNode ScopeNode2 { get; set; }
        [DataMember]
        public virtual ScopeNodeType ScopeNodeType { get; set; }
        [DataMember]
        public virtual ICollection<ScopeNodeChildParent> ScopeNodeChildParents { get; set; }
        [DataMember]
        public virtual ICollection<ScopeNodeChildParent> ScopeNodeChildParents1 { get; set; }
        [DataMember]
        public virtual ICollection<ScopeNodeReputation> ScopeNodeReputations { get; set; }
        [DataMember]
        public virtual ICollection<Town> Towns { get; set; }
    }
    
}
