//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace RevolutionDAL
{
    [DataContract(IsReference = true)]
    public partial class sysdiagram
    {
        #region Primitive Properties
        [DataMember]
        public virtual string name
        {
            get;
            set;
        }
        [DataMember]
        public virtual int principal_id
        {
            get;
            set;
        }
        [DataMember]
        public virtual int diagram_id
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<int> version
        {
            get;
            set;
        }
        [DataMember]
        public virtual byte[] definition
        {
            get;
            set;
        }

        #endregion
    }
}
